### ISSUE TITLE
Confusing references to "tracing attributes"

### ISSUE THREAD

**Issue by yurishkuro** [opentracing-contrib/python-tornado#1]
The README has sections like "if you wanted to trace the uri and method, then set `opentracing_traced_attributes = ['uri', 'method']`." What does it mean to "trace attributes"? Is it referring to capturing them as tags in the span?

**Comment by carlosalberto** [comment]
Yes, the tags. Sounds like I should use 'include' instead of 'trace' for this part :(

**Comment by yurishkuro** [comment]
"record" or "capture"

**Comment by alisonatwork** [comment]
@yurishkuro is it okay to close this issue with the change from #4?
